#!/usr/bin/env python3
"""Generate THIRD_PARTY_NOTICES.md from cargo metadata.

Deterministic: same lockfile in, same bytes out. Run from the repo root (or
pass --repo). The bundled zstd C library's BSD-3-Clause text is embedded
below because BSD requires reproducing the notice in binary distributions;
it is the LICENSE shipped inside the zstd-sys crate, verbatim.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

HEADER = """# Third-Party Notices

RetrievalKit is Copyright 2026 EGGYOLK YAZILIM TİCARET LİMİTED ŞİRKETİ and
licensed under Apache-2.0 (see `LICENSE` and `NOTICE`).

Binary distributions of RetrievalKit statically link the third-party Rust
crates and bundled C libraries listed below. Where a crate offers a choice
of licenses, RetrievalKit elects Apache-2.0 when offered, otherwise MIT.
This file is generated by `scripts/release/generate_third_party_notices.py`
from the checked-in `Cargo.lock`; regenerate it whenever dependencies change.
"""

# icu4x crates declare their license via license-file, so cargo metadata
# reports null; they are Unicode-3.0.
LICENSE_FALLBACKS = {"https://github.com/unicode-org/icu4x": "Unicode-3.0"}

ZSTD_NOTE = """## Bundled C libraries

### zstd (via the `zstd-sys` crate)

The zstd C library is dual-licensed BSD-3-Clause OR GPL-2.0; RetrievalKit
elects BSD-3-Clause. The following license text is reproduced verbatim from
the bundled sources:

```text
{zstd_license}
```

### SimSIMD (via the `simsimd` crate)

SimSIMD bundles C sources licensed Apache-2.0
(Copyright Ash Vardanian, https://github.com/ashvardanian/SimSIMD).
"""


def crate_rows(repo: Path) -> list[str]:
    metadata = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--locked"],
            cwd=repo,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    members = set(metadata["workspace_members"])
    rows = []
    for package in sorted(
        (p for p in metadata["packages"] if p["id"] not in members),
        key=lambda p: (p["name"], p["version"]),
    ):
        repository = package.get("repository") or ""
        license_id = package.get("license") or LICENSE_FALLBACKS.get(
            repository, "see repository"
        )
        rows.append(
            f"| {package['name']} | {package['version']} | {license_id} | {repository} |"
        )
    return rows


def zstd_license_text() -> str:
    root = Path.home() / ".cargo/registry/src"
    candidates = sorted(root.glob("*/zstd-sys-*/zstd/LICENSE"))
    if not candidates:
        raise SystemExit(
            "zstd-sys sources not found in the cargo registry; run `cargo fetch` first"
        )
    return candidates[-1].read_text(encoding="utf-8").strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    repo = args.repo.resolve()
    body = [
        HEADER,
        "## Rust crates\n",
        "| Crate | Version | License | Repository |",
        "| --- | --- | --- | --- |",
        *crate_rows(repo),
        "",
        ZSTD_NOTE.format(zstd_license=zstd_license_text()),
    ]
    (repo / "THIRD_PARTY_NOTICES.md").write_text("\n".join(body), encoding="utf-8")
    print("wrote THIRD_PARTY_NOTICES.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
