from os import PathLike
from typing import Final

BUILD_MODE: Final[str]
EMBEDDING_DIMENSION: Final[int]
ONNX_RUNTIME_VERSION: Final[str]

def _verify_package_runtime(path: str | PathLike[str]) -> None: ...

class EmbeddingError(Exception): ...
class EmbeddingInputError(ValueError): ...
class ModelUnavailableError(EmbeddingError): ...
class ArtifactError(EmbeddingError): ...
class DownloadError(ArtifactError): ...
class EmbeddingRuntimeError(EmbeddingError): ...

class ModelInfo:
    @property
    def identifier(self) -> str: ...
    @property
    def revision(self) -> str: ...
    @property
    def profile(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    @property
    def max_input_tokens(self) -> int: ...
    @property
    def produces_normalized_embeddings(self) -> bool: ...

class OnnxEmbedder:
    def __init__(
        self,
        *,
        local_only: bool = False,
        cache_directory: str | PathLike[str] | None = None,
        runtime_library_path: str | PathLike[str] | None = None,
    ) -> None: ...
    @staticmethod
    def load(
        *,
        local_only: bool = False,
        cache_directory: str | PathLike[str] | None = None,
        runtime_library_path: str | PathLike[str] | None = None,
    ) -> OnnxEmbedder: ...
    @staticmethod
    def prefetch(
        *,
        cache_directory: str | PathLike[str] | None = None,
        local_only: bool = False,
    ) -> None: ...
    @property
    def model_info(self) -> ModelInfo: ...
    def embed(self, text: str) -> list[float]: ...
    def embed_batch(self, texts: list[str]) -> list[list[float]]: ...
