#!/bin/sh

kotlin_java_major() {
  version=$1
  case "$version" in
    1.*)
      printf '%s\n' "$version" | sed 's/^1\.\([0-9][0-9]*\).*/\1/'
      ;;
    *)
      printf '%s\n' "$version" | sed 's/^\([0-9][0-9]*\).*/\1/'
      ;;
  esac
}

kotlin_java_setup_help() {
  printf '%s' 'Install a JDK 17 distribution, set JAVA_HOME to that installation, and put $JAVA_HOME/bin first on PATH. On macOS: export JAVA_HOME=$(/usr/libexec/java_home -v 17); export PATH="$JAVA_HOME/bin:$PATH". Verify the selection with "$JAVA_HOME/bin/java -version". Java 11 is the generated bytecode/runtime target, not the build JDK.'
}
