#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=java-support.sh
. "$SCRIPT_DIR/java-support.sh"

assert_equal() {
  expected=$1
  actual=$2
  label=$3
  if [ "$expected" != "$actual" ]; then
    echo "preflight test failed: $label: expected '$expected', got '$actual'" >&2
    exit 1
  fi
}

assert_contains() {
  value=$1
  expected=$2
  label=$3
  case "$value" in
    *"$expected"*) ;;
    *)
      echo "preflight test failed: $label: expected '$value' to contain '$expected'" >&2
      exit 1
      ;;
  esac
}

assert_equal "17" "$(kotlin_java_major "17.0.12")" "modern JDK major"
assert_equal "8" "$(kotlin_java_major "1.8.0_442")" "legacy JDK major"

SETUP_HELP=$(kotlin_java_setup_help)
assert_contains "$SETUP_HELP" "Install a JDK 17 distribution" "installation recovery"
assert_contains "$SETUP_HELP" 'export JAVA_HOME=$(/usr/libexec/java_home -v 17)' "macOS selection"
assert_contains "$SETUP_HELP" 'Verify the selection with "$JAVA_HOME/bin/java -version"' "selection verification"
assert_contains "$SETUP_HELP" "Java 11 is the generated bytecode/runtime target, not the build JDK" "toolchain distinction"

TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/retrievalkit-kotlin-preflight.XXXXXX")
cleanup() {
  if [ -d "$TEST_ROOT" ]; then
    rm -r "$TEST_ROOT"
  fi
}
trap cleanup EXIT HUP INT TERM

mkdir -p "$TEST_ROOT/bin" "$TEST_ROOT/jdk17/bin" "$TEST_ROOT/jdk25/bin"

cat >"$TEST_ROOT/bin/uname" <<'EOF'
#!/bin/sh
case "${1:-}" in
  -s) echo Darwin ;;
  -m) echo arm64 ;;
  *) exit 2 ;;
esac
EOF

cat >"$TEST_ROOT/jdk17/bin/java" <<'EOF'
#!/bin/sh
echo 'openjdk version "17.0.12" 2024-07-16' >&2
EOF

cat >"$TEST_ROOT/jdk25/bin/java" <<'EOF'
#!/bin/sh
echo 'openjdk version "25.0.2" 2026-01-20' >&2
EOF

chmod +x \
  "$TEST_ROOT/bin/uname" \
  "$TEST_ROOT/jdk17/bin/java" \
  "$TEST_ROOT/jdk25/bin/java"

PREFLIGHT_OUTPUT=$(
  JAVA_HOME="$TEST_ROOT/jdk17" \
    PATH="$TEST_ROOT/bin:$PATH" \
    "$SCRIPT_DIR/preflight.sh" jvm
)
assert_contains "$PREFLIGHT_OUTPUT" "detected 17.0.12 at $TEST_ROOT/jdk17/bin/java" "JAVA_HOME selection"
assert_contains "$PREFLIGHT_OUTPUT" "Generated bytecode/runtime target: Java 11" "runtime target output"

set +e
UNSUPPORTED_OUTPUT=$(
  JAVA_HOME="$TEST_ROOT/jdk25" \
    PATH="$TEST_ROOT/bin:$PATH" \
    "$SCRIPT_DIR/preflight.sh" jvm 2>&1
)
UNSUPPORTED_STATUS=$?
set -e
assert_equal "1" "$UNSUPPORTED_STATUS" "unsupported JDK exit status"
assert_contains "$UNSUPPORTED_OUTPUT" "detected Java 25.0.2 from $TEST_ROOT/jdk25/bin/java" "unsupported JDK source"
assert_contains "$UNSUPPORTED_OUTPUT" "Install a JDK 17 distribution" "unsupported JDK recovery"

echo "Kotlin preflight tests passed"
