#!/bin/sh
set -eu

MODE=${1:-all}
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=java-support.sh
. "$SCRIPT_DIR/java-support.sh"

fail() {
  echo "Kotlin wrapper preflight failed: $*" >&2
  exit 1
}

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "required tool '$1' was not found on PATH."
  fi
}

case "$MODE" in
  jvm|android|all) ;;
  *)
    echo "usage: $0 [jvm|android|all]" >&2
    exit 2
    ;;
esac

if [ -n "${JAVA_HOME:-}" ]; then
  JAVA_BIN="$JAVA_HOME/bin/java"
  if [ ! -x "$JAVA_BIN" ]; then
    fail "JAVA_HOME '$JAVA_HOME' does not contain an executable bin/java. $(kotlin_java_setup_help)"
  fi
else
  if ! command -v java >/dev/null 2>&1; then
    fail "Java was not found on PATH. $(kotlin_java_setup_help)"
  fi
  JAVA_BIN=$(command -v java)
fi

JAVA_VERSION_OUTPUT=$("$JAVA_BIN" -version 2>&1) ||
  fail "could not run '$JAVA_BIN -version'. $(kotlin_java_setup_help)"
JAVA_VERSION=$(printf '%s\n' "$JAVA_VERSION_OUTPUT" | sed -n '1s/.*version "\([^"]*\)".*/\1/p')
JAVA_MAJOR=$(kotlin_java_major "$JAVA_VERSION")
if [ -z "$JAVA_VERSION" ] || [ "$JAVA_MAJOR" != "17" ]; then
  fail "JDK 17 is required to build RetrievalKit; detected Java ${JAVA_VERSION:-unknown} from $JAVA_BIN. $(kotlin_java_setup_help)"
fi

require_tool cargo

HOST_OS=$(uname -s)
HOST_ARCH=$(uname -m)
if [ "$HOST_OS" != "Darwin" ] || [ "$HOST_ARCH" != "arm64" ]; then
  fail "the initial Kotlin/JVM native package requires macOS arm64; detected $HOST_OS $HOST_ARCH."
fi

CARGO_VERSION=$(cargo --version)

echo "Kotlin wrapper preflight passed"
echo "  Java build toolchain: required JDK 17; detected $JAVA_VERSION at $JAVA_BIN"
echo "  Generated bytecode/runtime target: Java 11"
echo "  Rust: required cargo on PATH; detected $CARGO_VERSION"
echo "  JVM host: required Darwin arm64; detected $HOST_OS $HOST_ARCH"

if [ "$MODE" = "android" ] || [ "$MODE" = "all" ]; then
  require_tool rustup
  if ! rustup target list --installed | grep -qx 'aarch64-linux-android'; then
    fail "Rust target aarch64-linux-android is required; run 'rustup target add aarch64-linux-android'."
  fi

  : "${ANDROID_NDK_HOME:=$HOME/Library/Android/sdk/ndk/26.1.10909125}"
  NDK_PROPERTIES="$ANDROID_NDK_HOME/source.properties"
  if [ ! -f "$NDK_PROPERTIES" ]; then
    fail "Android NDK metadata not found at $NDK_PROPERTIES. Set ANDROID_NDK_HOME to the installed NDK 26 directory."
  fi
  NDK_VERSION=$(
    sed -n \
      's/^[[:space:]]*Pkg\.Revision[[:space:]]*=[[:space:]]*\([^[:space:]]*\).*$/\1/p' \
      "$NDK_PROPERTIES" |
      head -n 1
  )
  NDK_MAJOR=${NDK_VERSION%%.*}
  if [ -z "$NDK_VERSION" ] || [ "$NDK_MAJOR" != "26" ]; then
    fail "Android NDK 26 is required; detected NDK ${NDK_VERSION:-unknown} at $ANDROID_NDK_HOME. Set ANDROID_NDK_HOME to the installed NDK 26 directory."
  fi

  TOOLCHAIN="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin"
  LINKER="$TOOLCHAIN/aarch64-linux-android24-clang"
  if [ ! -x "$LINKER" ]; then
    fail "Android NDK 26 arm64 linker not found at $LINKER. Set ANDROID_NDK_HOME to the installed NDK 26 directory."
  fi

  echo "  Android: required API 24 arm64-v8a with NDK 26; detected NDK $NDK_VERSION at $ANDROID_NDK_HOME"
fi
